---
- name: provision stack
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: create or update the CloudFormation stack
    cloudformation:
      stack_name: "{{ stack_name }}"
      state: present
      region: "{{ aws_region }}"
      disable_rollback: true
      template: files/cloudformation.json
    args:
      template_parameters:
        KeyName: jmartin
        DiskType: ephemeral
        InstanceType: m1.small
        ClusterSize: 3
    register: stack
  - name: show stack outputs
    debug: msg="My stack outputs are {{stack.stack_outputs}}"